set-option -g default-shell /bin/zsh
set -g default-terminal xterm-256color
set -g mouse on

bind -n End send-key C-e
bind -n Home send-key C-a

# remap prefix from 'C-b' to 'C-l'
unbind C-b
set-option -g prefix C-l
bind-key C-l send-prefix

# split panes using | and -
unbind "'"
bind "'" split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# don't rename windows automatically
set-option -g allow-rename off

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf
